# Generated by Django 4.0.4 on 2022-06-04 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='type',
            field=models.CharField(choices=[('F', 'Featured'), ('L', 'Latest')], default='F', max_length=2),
            preserve_default=False,
        ),
    ]
