# Generated by Django 4.0.4 on 2022-06-13 23:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_product_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('P', 'Phones'), ('T', 'Tablets'), ('C', 'Computing'), ('E', 'Electronics'), ('H', 'Home & Kitchen'), ('A', 'Accessories'), ('CA', 'Camera'), ('FB', 'Food & Beverages'), ('CL', 'Clothing'), ('S', 'Sound & Vision')], max_length=3),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('body', models.TextField(verbose_name='Enter your commment...')),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='store.product')),
            ],
        ),
    ]
