# Generated by Django 4.0.4 on 2022-05-25 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_orederitem_order'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OrederItem',
            new_name='OrderItem',
        ),
    ]
