# Generated by Django 4.0.4 on 2022-05-31 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0016_alter_product_discount_price_alter_product_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='billingaddress',
            old_name='aprtment_address',
            new_name='apartment_address',
        ),
    ]
